import {Injectable} from '@angular/core';
import {Song} from './songs/song';
import {Observable, of} from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class SongService {

  songs: Song[] = [
    {name: `Feel The Love`, trackIndex: 1, album: 'Kids See Ghosts'},
    {name: `Fire`, trackIndex: 2, album: 'Kids See Ghosts'},
    {name: `4th Dimension`, trackIndex: 3, album: 'Kids See Ghosts'},
    {name: `Freeee (Ghost Town Pt.2)`, trackIndex: 4, album: 'Kids See Ghosts'},
    {name: `Reborn`, trackIndex: 5, album: 'Kids See Ghosts'},
    {name: `Kids See Ghosts`, trackIndex: 6, album: 'Kids See Ghosts'},
    {name: `Cudi Montage`, trackIndex: 7, album: 'Kids See Ghosts'},

    {name: `I Thought About Killing You`, trackIndex: 1, album: 'Ye'},
    {name: `Yikes`, trackIndex: 2, album: 'Ye'},
    {name: `All Mine`, trackIndex: 3, album: 'Ye'},
    {name: `Wouldn't Leave`, trackIndex: 4, album: 'Ye'},
    {name: `No Mistakes`, trackIndex: 5, album: 'Ye'},
    {name: `Ghost Town`, trackIndex: 6, album: 'Ye'},
    {name: `Violent Crimes`, trackIndex: 7, album: 'Ye'},

    {name: `Free Smoke`, trackIndex: 1, album: 'More Life'},
    {name: `No Long Talk`, trackIndex: 2, album: 'More Life'},
    {name: `Passionfruit`, trackIndex: 3, album: 'More Life'},
    {name: `Jorja Interlude`, trackIndex: 4, album: 'More Life'},
    {name: `Get It Together`, trackIndex: 5, album: 'More Life'},
    {name: `Madiba Riddim`, trackIndex: 6, album: 'More Life'},
    {name: `Blem`, trackIndex: 7, album: 'More Life'},
    {name: `4422`, trackIndex: 8, album: 'More Life'},
    {name: `Gyalchester`, trackIndex: 9, album: 'More Life'},
    {name: `Skepta Interlude`, trackIndex: 10, album: 'More Life'},
    {name: `Portland`, trackIndex: 11, album: 'More Life'},
    {name: `Sacrifices`, trackIndex: 12, album: 'More Life'},
    {name: `Nothings Into Somethings`, trackIndex: 13, album: 'More Life'},
    {name: `Teenage Fever`, trackIndex: 14, album: 'More Life'},
    {name: `KMT`, trackIndex: 15, album: 'More Life'},
    {name: `Lose You`, trackIndex: 16, album: 'More Life'},
    {name: `Can't Have Everything`, trackIndex: 17, album: 'More Life'},
    {name: `Glow`, trackIndex: 18, album: 'More Life'},
    {name: `Since Way Back`, trackIndex: 19, album: 'More Life'},
    {name: `Fake Love`, trackIndex: 20, album: 'More Life'},
    {name: `Ice Melts`, trackIndex: 21, album: 'More Life'},
    {name: `Do Not Disturb`, trackIndex: 22, album: 'More Life'},

    {name: `Keep The Family Close`, trackIndex: 1, album: 'Views'},
    {name: `9`, trackIndex: 2, album: 'Views'},
    {name: `U With Me?`, trackIndex: 3, album: 'Views'},
    {name: `Feel No Ways`, trackIndex: 4, album: 'Views'},
    {name: `Hype`, trackIndex: 5, album: 'Views'},
    {name: `Weston Road Flows`, trackIndex: 6, album: 'Views'},
    {name: `Redemption`, trackIndex: 7, album: 'Views'},
    {name: `With You`, trackIndex: 8, album: 'Views'},
    {name: `Faithful`, trackIndex: 9, album: 'Views'},
    {name: `Still Here`, trackIndex: 10, album: 'Views'},
    {name: `Controlla`, trackIndex: 11, album: 'Views'},
    {name: `One Dance`, trackIndex: 12, album: 'Views'},
    {name: `Grammys`, trackIndex: 13, album: 'Views'},
    {name: `Childs Play`, trackIndex: 14, album: 'Views'},
    {name: `Pop Style`, trackIndex: 15, album: 'Views'},
    {name: `Too Good`, trackIndex: 16, album: 'Views'},
    {name: `Summers Over Interlude`, trackIndex: 17, album: 'Views'},
    {name: `Fire & Desire`, trackIndex: 18, album: 'Views'},
    {name: `Views`, trackIndex: 19, album: 'Views'},
    {name: `Hotline Bling`, trackIndex: 20, album: 'Views'},

    {name: `No Cap`, trackIndex: 1, album: 'Super Slimey'},
    {name: `Three`, trackIndex: 2, album: 'Super Slimey'},
    {name: `All Da Smoke`, trackIndex: 3, album: 'Super Slimey'},
    {name: `200`, trackIndex: 4, album: 'Super Slimey'},
    {name: `Cruise Ship`, trackIndex: 5, album: 'Super Slimey'},
    {name: `Patek Water`, trackIndex: 6, album: 'Super Slimey'},
    {name: `Feed Me Dope`, trackIndex: 7, album: 'Super Slimey'},
    {name: `Drip On Me`, trackIndex: 8, album: 'Super Slimey'},
    {name: `Real Love`, trackIndex: 9, album: 'Super Slimey'},
    {name: `4 Da Gang`, trackIndex: 10, album: 'Super Slimey'},
    {name: `Killed Before`, trackIndex: 11, album: 'Super Slimey'},
    {name: `Mink Flow`, trackIndex: 12, album: 'Super Slimey'},
    {name: `Group Home`, trackIndex: 13, album: 'Super Slimey'},

    {name: `My Collection`, trackIndex: 1, album: ''},
    {name: `Coming Out Strong`, trackIndex: 2, album: ''},
    {name: `Lookin Exotic`, trackIndex: 3, album: ''},
    {name: `Damage`, trackIndex: 4, album: ''},
    {name: `Use Me`, trackIndex: 5, album: ''},
    {name: `Incredible`, trackIndex: 6, album: ''},
    {name: `Testify`, trackIndex: 7, album: ''},
    {name: `Fresh Air`, trackIndex: 8, album: ''},
    {name: `Neva Missa Lost`, trackIndex: 9, album: ''},
    {name: `Keep Quiet`, trackIndex: 10, album: ''},
    {name: `Hallucinating`, trackIndex: 11, album: ''},
    {name: `I Thank U`, trackIndex: 12, album: ''},
    {name: `New Illuminati`, trackIndex: 13, album: ''},
    {name: `Turn On Me`, trackIndex: 14, album: ''},
    {name: `Selfish`, trackIndex: 15, album: ''},
    {name: `Solo`, trackIndex: 16, album: ''},
    {name: `Sorry`, trackIndex: 17, album: ''},
    {name: `PIE`, trackIndex: 18, album: ''},
    {name: `You Da Baddest`, trackIndex: 19, album: ''},

    {name: `The Beautiful & Damned`, trackIndex: 1, album: 'The Beautiful & Damned'},
    {name: `Pray For Me`, trackIndex: 2, album: 'The Beautiful & Damned'},
    {name: `Him & I (with Halsey)`, trackIndex: 3, album: 'The Beautiful & Damned'},
    {name: `But A Dream`, trackIndex: 4, album: 'The Beautiful & Damned'},
    {name: `Sober`, trackIndex: 5, album: 'The Beautiful & Damned'},
    {name: `Legend`, trackIndex: 6, album: 'The Beautiful & Damned'},
    {name: `No Limit`, trackIndex: 7, album: 'The Beautiful & Damned'},
    {name: `The Pan`, trackIndex: 8, album: 'The Beautiful & Damned'},
    {name: `That's A Lot`, trackIndex: 9, album: 'The Beautiful & Damned'},
    {name: `Pick Me Up`, trackIndex: 10, album: 'The Beautiful & Damned'},
    {name: `Gotdamn`, trackIndex: 11, album: 'The Beautiful & Damned'},
    {name: `Leviathan`, trackIndex: 12, album: 'The Beautiful & Damned'},
    {name: `Crash & Burn`, trackIndex: 13, album: 'The Beautiful & Damned'},
    {name: `Summer In December`, trackIndex: 14, album: 'The Beautiful & Damned'},
    {name: `Charles Brown`, trackIndex: 15, album: 'The Beautiful & Damned'},
    {name: `No Less`, trackIndex: 16, album: 'The Beautiful & Damned'},
    {name: `Mama Always Told Me`, trackIndex: 17, album: 'The Beautiful & Damned'},
    {name: `Fly Away`, trackIndex: 18, album: 'The Beautiful & Damned'},
    {name: `Love Is Gone`, trackIndex: 19, album: 'The Beautiful & Damned'},
    {name: `Eazy`, trackIndex: 20, album: 'The Beautiful & Damned'},

    {name: `Intro`, trackIndex: 1, album: `When It's Dark Out`},
    {name: `Random`, trackIndex: 2, album: `When It's Dark Out`},
    {name: `Me, Myself, & I`, trackIndex: 3, album: `When It's Dark Out`},
    {name: `One Of Them`, trackIndex: 4, album: `When It's Dark Out`},
    {name: `Drifting`, trackIndex: 5, album: `When It's Dark Out`},
    {name: `Of All Things`, trackIndex: 6, album: `When It's Dark Out`},
    {name: `Order More`, trackIndex: 7, album: `When It's Dark Out`},
    {name: `Calm Down`, trackIndex: 8, album: `When It's Dark Out`},
    {name: `Don't Let Me Go`, trackIndex: 9, album: `When It's Dark Out`},
    {name: `You Got Me`, trackIndex: 10, album: `When It's Dark Out`},
    {name: `What If`, trackIndex: 11, album: `When It's Dark Out`},
    {name: `Sad Boy`, trackIndex: 12, album: `When It's Dark Out`},
    {name: `Some Kind Of Drug`, trackIndex: 13, album: `When It's Dark Out`},
    {name: `Think About You`, trackIndex: 14, album: `When It's Dark Out`},
    {name: `Everything Will Be Ok`, trackIndex: 15, album: `When It's Dark Out`},
    {name: `For This`, trackIndex: 16, album: `When It's Dark Out`},
    {name: `Nothing To Me`, trackIndex: 17, album: `When It's Dark Out`},

    {name: `Higher We Go - Intro`, trackIndex: 1, album: `Culture II`},
    {name: `Supastars`, trackIndex: 2, album: `Culture II`},
    {name: `Narcos`, trackIndex: 3, album: `Culture II`},
    {name: `BBO (Bad Bitches Only)`, trackIndex: 4, album: `Culture II`},
    {name: `Auto Pilot`, trackIndex: 5, album: `Culture II`},
    {name: `Walk It Talk It`, trackIndex: 6, album: `Culture II`},
    {name: `Emoji A Chain`, trackIndex: 7, album: `Culture II`},
    {name: `CC`, trackIndex: 8, album: `Culture II`},
    {name: `Stir Fry`, trackIndex: 9, album: `Culture II`},
    {name: `Too Much Jewelry`, trackIndex: 10, album: `Culture II`},
    {name: `Gang Gang`, trackIndex: 11, album: `Culture II`},
    {name: `White Sand`, trackIndex: 12, album: `Culture II`},
    {name: `Crown The Kings`, trackIndex: 13, album: `Culture II`},
    {name: `Flooded`, trackIndex: 14, album: `Culture II`},
    {name: `Beast`, trackIndex: 15, album: `Culture II`},
    {name: `Open It Up`, trackIndex: 16, album: `Culture II`},
    {name: `MotorSport`, trackIndex: 17, album: `Culture II`},
    {name: `Movin'Too Fast`, trackIndex: 18, album: `Culture II`},
    {name: `Work Hard`, trackIndex: 19, album: `Culture II`},
    {name: `Notice Me`, trackIndex: 20, album: `Culture II`},
    {name: `Too Playa`, trackIndex: 21, album: `Culture II`},
    {name: `Made Men`, trackIndex: 22, album: `Culture II`},
    {name: `Top Down On Da NAWF`, trackIndex: 23, album: `Culture II`},
    {name: `Culture National Anthem - Outro`, trackIndex: 24, album: `Culture II`},

    {name: `Culture (feat. DJ Khaled)`, trackIndex: 1, album: `Culture`},
    {name: `T-Shirt`, trackIndex: 2, album: `Culture`},
    {name: `Call Casting`, trackIndex: 3, album: `Culture`},
    {name: `Bad And Boujee (feat. Lil Uzi Vert)`, trackIndex: 4, album: `Culture`},
    {name: `Get Right Witcha`, trackIndex: 5, album: `Culture`},
    {name: `Slippery (feat. Gucci Mane)`, trackIndex: 6, album: `Culture`},
    {name: `Big On Big`, trackIndex: 7, album: `Culture`},
    {name: `What The Price`, trackIndex: 8, album: `Culture`},
    {name: `Brown Paper Bag`, trackIndex: 9, album: `Culture`},
    {name: `Deadz (feat. 2 Chainz)`, trackIndex: 10, album: `Culture`},
    {name: `All Ass`, trackIndex: 11, album: `Culture`},
    {name: `Kelly Price (feat. Travis Scott)`, trackIndex: 12, album: `Culture`},
    {name: `Out Yo Way`, trackIndex: 13, album: `Culture`},

    {name: `Paranoid`, trackIndex: 1, album: `Beerbongs & Bentleys`},
    {name: `Spoil My Night (feat. Swae Lee)`, trackIndex: 2, album: `Beerbongs & Bentleys`},
    {name: `Rich & Sad`, trackIndex: 3, album: `Beerbongs & Bentleys`},
    {name: `Zack And Codeine`, trackIndex: 4, album: `Beerbongs & Bentleys`},
    {name: `Takin' Shots`, trackIndex: 5, album: `Beerbongs & Bentleys`},
    {name: `Rockstar (feat. 21 Savage)`, trackIndex: 6, album: `Beerbongs & Bentleys`},
    {name: `Over Now`, trackIndex: 7, album: `Beerbongs & Bentleys`},
    {name: `Psycho (feat. Ty Dolla $ign)`, trackIndex: 8, album: `Beerbongs & Bentleys`},
    {name: `Better Now`, trackIndex: 9, album: `Beerbongs & Bentleys`},
    {name: `Ball For Me (feat. Nicki Minaj)`, trackIndex: 10, album: `Beerbongs & Bentleys`},
    {name: `Otherside`, trackIndex: 11, album: `Beerbongs & Bentleys`},
    {name: `Stay`, trackIndex: 12, album: `Beerbongs & Bentleys`},
    {name: `Blame It On Me`, trackIndex: 13, album: `Beerbongs & Bentleys`},
    {name: `Same Bitches (feat. G-Eazy & YG)`, trackIndex: 14, album: `Beerbongs & Bentleys`},
    {name: `Jonestown (Interlude)`, trackIndex: 15, album: `Beerbongs & Bentleys`},
    {name: `92 Explorer`, trackIndex: 16, album: `Beerbongs & Bentleys`},
    {name: `Candy Paint`, trackIndex: 17, album: `Beerbongs & Bentleys`},
    {name: `Sugar Wraith`, trackIndex: 18, album: `Beerbongs & Bentleys`},

    {name: `Broken Whiskey Glass`, trackIndex: 1, album: `Stoney`},
    {name: `Big Lie`, trackIndex: 2, album: `Stoney`},
    {name: `Deja Vu`, trackIndex: 3, album: `Stoney`},
    {name: `No Option`, trackIndex: 4, album: `Stoney`},
    {name: `Cold`, trackIndex: 5, album: `Stoney`},
    {name: `White Iverson`, trackIndex: 6, album: `Stoney`},
    {name: `I Fall Apart`, trackIndex: 7, album: `Stoney`},
    {name: `Patient`, trackIndex: 8, album: `Stoney`},
    {name: `Go Flex`, trackIndex: 9, album: `Stoney`},
    {name: `Feel`, trackIndex: 10, album: `Stoney`},
    {name: `Too Young`, trackIndex: 11, album: `Stoney`},
    {name: `Congratulations`, trackIndex: 12, album: `Stoney`},
    {name: `Up There`, trackIndex: 13, album: `Stoney`},
    {name: `Yours Truly, Austin Post`, trackIndex: 14, album: `Stoney`},
    {name: `Leave`, trackIndex: 15, album: `Stoney`},
    {name: `Hit This Hard`, trackIndex: 16, album: `Stoney`},
    {name: `Money Made Me Do It`, trackIndex: 17, album: `Stoney`},
    {name: `Feeling Whitney`, trackIndex: 18, album: `Stoney`},

    {name: `Konnichiwa`, trackIndex: 1, album: `Konnichiwa`},
    {name: `Lyrics`, trackIndex: 2, album: `Konnichiwa`},
    {name: `Corn On The Curb`, trackIndex: 3, album: `Konnichiwa`},
    {name: `Crime Riddim`, trackIndex: 4, album: `Konnichiwa`},
    {name: `It Ain't Safe`, trackIndex: 5, album: `Konnichiwa`},
    {name: `Ladies Hit Squad`, trackIndex: 6, album: `Konnichiwa`},
    {name: `Numbers`, trackIndex: 7, album: `Konnichiwa`},
    {name: `Man`, trackIndex: 8, album: `Konnichiwa`},
    {name: `Shutdown`, trackIndex: 9, album: `Konnichiwa`},
    {name: `That's Not Me`, trackIndex: 10, album: `Konnichiwa`},
    {name: `Detox`, trackIndex: 11, album: `Konnichiwa`},
    {name: `Text Me Back`, trackIndex: 12, album: `Konnichiwa`},

    {name: `If You Know You Know`, trackIndex: 1, album: `DAYTONA`},
    {name: `The Games We Play`, trackIndex: 2, album: `DAYTONA`},
    {name: `Hard Piano`, trackIndex: 3, album: `DAYTONA`},
    {name: `Come Back Baby`, trackIndex: 4, album: `DAYTONA`},
    {name: `Santeria`, trackIndex: 5, album: `DAYTONA`},
    {name: `What Would Meek Do?`, trackIndex: 6, album: `DAYTONA`},
    {name: `Infrared`, trackIndex: 7, album: `DAYTONA`},

    {name: `Sweet Love`, trackIndex: 1, album: `Sounds From The Other Side`},
    {name: `Come Closer`, trackIndex: 2, album: `Sounds From The Other Side`},
    {name: `Naughty Ride`, trackIndex: 3, album: `Sounds From The Other Side`},
    {name: `African Bad Gyal`, trackIndex: 4, album: `Sounds From The Other Side`},
    {name: `Daddy Yo`, trackIndex: 5, album: `Sounds From The Other Side`},
    {name: `One For Me`, trackIndex: 6, album: `Sounds From The Other Side`},
    {name: `Picture Perfect`, trackIndex: 7, album: `Sounds From The Other Side`},
    {name: `Nobody`, trackIndex: 8, album: `Sounds From The Other Side`},
    {name: `Sexy`, trackIndex: 9, album: `Sounds From The Other Side`},
    {name: `All For Love`, trackIndex: 10, album: `Sounds From The Other Side`},
    {name: `Dirty Wine`, trackIndex: 11, album: `Sounds From The Other Side`},
    {name: `Gbese`, trackIndex: 12, album: `Sounds From The Other Side`},

    {name: `All Of You`, trackIndex: 1, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `Back When`, trackIndex: 2, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `New Skul Tinz`, trackIndex: 3, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `Video`, trackIndex: 4, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `Ekuro`, trackIndex: 5, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `Down`, trackIndex: 6, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `No Visa`, trackIndex: 7, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `Enter The Center`, trackIndex: 8, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `Dollars In The Bank`, trackIndex: 9, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `Sade`, trackIndex: 10, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `Gbon Gbon`, trackIndex: 11, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `Feel Alright`, trackIndex: 12, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `Mary Jane`, trackIndex: 13, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `For You`, trackIndex: 14, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `Overseas`, trackIndex: 15, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `Dami Duro`, trackIndex: 16, album: `Omo Baba Olowo (O.B.O) - The Genesis`},
    {name: `Bless Me`, trackIndex: 17, album: `Omo Baba Olowo (O.B.O) - The Genesis`},

    {name: `Common Sense`, trackIndex: 1, album: `Common Sense`},
    {name: `Bouff Daddy`, trackIndex: 2, album: `Common Sense`},
    {name: `Clartin`, trackIndex: 3, album: `Common Sense`},
    {name: `Leave Me`, trackIndex: 4, album: `Common Sense`},
    {name: `Closed Doors`, trackIndex: 5, album: `Common Sense`},
    {name: `Did You See`, trackIndex: 6, album: `Common Sense`},
    {name: `Like Your Style`, trackIndex: 7, album: `Common Sense`},
    {name: `Plottin`, trackIndex: 8, album: `Common Sense`},
    {name: `Sweet Cheeks`, trackIndex: 9, album: `Common Sense`},
    {name: `Fisherman`, trackIndex: 10, album: `Common Sense`},
    {name: `Good Time`, trackIndex: 11, album: `Common Sense`},
    {name: `Spirit`, trackIndex: 12, album: `Common Sense`},
    {name: `Mash Up`, trackIndex: 13, album: `Common Sense`},
    {name: `Goodies`, trackIndex: 14, album: `Common Sense`},
    {name: `Good Luck Chale`, trackIndex: 15, album: `Common Sense`},
    {name: `Who Are You`, trackIndex: 16, album: `Common Sense`},
    {name: `Friendly`, trackIndex: 17, album: `Common Sense`},

    {name: `Champions League`, trackIndex: 1, album: `7 Days`},
    {name: `Told You`, trackIndex: 2, album: `7 Days`},
    {name: `Wo Wo Wo`, trackIndex: 3, album: `7 Days`},
    {name: `On My Life`, trackIndex: 4, album: `7 Days`},
    {name: `Robbery Remix`, trackIndex: 5, album: `7 Days`},
    {name: `Khalas`, trackIndex: 6, album: `7 Days`},
    {name: `Sauce`, trackIndex: 7, album: `7 Days`},
    {name: `Cold Summer - Frept Freestyle`, trackIndex: 8, album: `7 Days`},
    {name: `Ask Flipz`, trackIndex: 9, album: `7 Days`},
    {name: `Last Night In LA - Konan Freestyle`, trackIndex: 10, album: `7 Days`},
    {name: `Get A Stack`, trackIndex: 11, album: `7 Days`},

    {name: `Don't Lie`, trackIndex: 1, album: `7 Nights`},
    {name: `For Me`, trackIndex: 2, album: `7 Nights`},
    {name: `Ride For You`, trackIndex: 3, album: `7 Nights`},
    {name: `Wrongs`, trackIndex: 4, album: `7 Nights`},
    {name: `Save Some`, trackIndex: 5, album: `7 Nights`},
    {name: `So Lit`, trackIndex: 6, album: `7 Nights`},
    {name: `Same Sh*t`, trackIndex: 7, album: `7 Nights`},
    {name: `One More Time`, trackIndex: 8, album: `7 Nights`},
    {name: `The One`, trackIndex: 9, album: `7 Nights`},
    {name: `Take Time`, trackIndex: 10, album: `7 Nights`},

    {name: `Vroom`, trackIndex: 1, album: `Vroom`},

    {name: `Answerphone (feat. Yxng Bane)`, trackIndex: 1, album: `Answerphone (feat. Yxng Bane)`},

    {name: `Corner (feat. Maleek Berry)`, trackIndex: 1, album: `Corner (feat. Maleek Berry)`},

    {name: `Rihanna`, trackIndex: 1, album: `Rihanna`},

    {name: `Fine Wine`, trackIndex: 1, album: `Fine Wine`},

    {name: `Sex Like Me`, trackIndex: 1, album: `Sex Like Me`},

    {name: `Body`, trackIndex: 1, album: `Body`},

    {name: `Fill Me In`, trackIndex: 1, album: `Fill Me In`},

    {name: `Dangerous (feat. Sam Martin)`, trackIndex: 1, album: `Listen`},
    {name: `What I Did For Love (feat. Emeli Sande)`, trackIndex: 2, album: `Listen`},
    {name: `No Money No Love (feat. Elliphant & Ms. Dynamite)`, trackIndex: 3, album: `Listen`},
    {name: `Lovers On The Sun (feat. Sam Martin)`, trackIndex: 4, album: `Listen`},
    {name: `Goodbey Friend (feat. The Script)`, trackIndex: 5, album: `Listen`},
    {name: `Lift Me Up (feat. nico & Vinz, Ladysmith Black Mambazo)`, trackIndex: 6, album: `Listen`},
    {name: `Listen 9feat. John Legend)`, trackIndex: 7, album: `Listen`},
    {name: `Bang My Head (feat. Sia)`, trackIndex: 8, album: `Listen`},
    {name: `Yesterday (feat. Bebe Rexha)`, trackIndex: 9, album: `Listen`},
    {name: `Hey Mama (feat. Nicki Minaj, Bebe Rexha & Afrojack)`, trackIndex: 10, album: `Listen`},
    {name: `Sun Goes Down (feat. MAGIC! & Sonny Wilson)`, trackIndex: 11, album: `Listen`},
    {name: `S.T.O.P (feat. Ryan Tedder)`, trackIndex: 12, album: `Listen`},
    {name: `I'll Keep Loving You (feat. Birdy & Jaymes Young)`, trackIndex: 13, album: `Listen`},
    {name: `The Whisperer (feat. Sia)`, trackIndex: 14, album: `Listen`},
    {name: `Bad (feat. Vassy)`, trackIndex: 15, album: `Listen`},
    {name: `Rise (feat. Skylar Grey)`, trackIndex: 16, album: `Listen`},
    {name: `Shot Me Down (feat. Skylar Grey)`, trackIndex: 17, album: `Listen`},
    {name: `Dangerous (feat. Sam Martin) - Robin Schulz Remix; Radio Edit`, trackIndex: 18, album: `Listen`},

    {name: `Bones`, trackIndex: 1, album: `Million Dollar Mug Shot`},
    {name: `Stoli`, trackIndex: 2, album: `Million Dollar Mug Shot`},
    {name: `One Of These Days (feat. Bubba Sparxxx)`, trackIndex: 3, album: `Million Dollar Mug Shot`},
    {name: `Pay Day`, trackIndex: 4, album: `Million Dollar Mug Shot`},
    {name: `WRBN`, trackIndex: 5, album: `Million Dollar Mug Shot`},
    {name: `Cool`, trackIndex: 6, album: `Million Dollar Mug Shot`},
    {name: `I Believe You`, trackIndex: 7, album: `Million Dollar Mug Shot`},
    {name: `Motel Room (feat. Rittz)`, trackIndex: 8, album: `Million Dollar Mug Shot`},
    {name: `Greatest Unreleased`, trackIndex: 9, album: `Million Dollar Mug Shot`},
    {name: `Shoebox`, trackIndex: 10, album: `Million Dollar Mug Shot`},
    {name: `No Shit`, trackIndex: 11, album: `Million Dollar Mug Shot`},
    {name: `Outer Space`, trackIndex: 12, album: `Million Dollar Mug Shot`},
    {name: `Love Synthetic`, trackIndex: 13, album: `Million Dollar Mug Shot`},
    {name: `Into The Night`, trackIndex: 14, album: `Million Dollar Mug Shot`},
    {name: `Dummy`, trackIndex: 15, album: `Million Dollar Mug Shot`},
    {name: `Keep On Smiling`, trackIndex: 16, album: `Million Dollar Mug Shot`},

    {name: `I Am Free`, trackIndex: 1, album: `I Am Free`},

    {name: `Children`, trackIndex: 1, album: `Children`},

    {name: `Antidote`, trackIndex: 1, album: `Antidote`},

    {name: `Young`, trackIndex: 1, album: `Young`},

    {name: `Stop Being Yourself`, trackIndex: 1, album: `Next Season`},
    {name: `Drifting Away`, trackIndex: 2, album: `Next Season`},
    {name: `Faces`, trackIndex: 3, album: `Next Season`},
    {name: `Walking By`, trackIndex: 4, album: `Next Season`},
    {name: `Hold Tight`, trackIndex: 5, album: `Next Season`},
    {name: `Down For You`, trackIndex: 6, album: `Next Season`},
    {name: `The Wave`, trackIndex: 7, album: `Next Season`},
    {name: `Everything Is Fine`, trackIndex: 8, album: `Next Season`},
    {name: `The Searchers`, trackIndex: 9, album: `Next Season`},
    {name: `Wherever`, trackIndex: 10, album: `Next Season`},
    {name: `Everyone But Me`, trackIndex: 11, album: `Next Season`},
    {name: `Runaway`, trackIndex: 12, album: `Next Season`},
    {name: `Falling Dwn`, trackIndex: 13, album: `Next Season`},
    {name: `Mood`, trackIndex: 14, album: `Next Season`},
    {name: `Get What You Give`, trackIndex: 15, album: `Next Season`},
    {name: `Overused`, trackIndex: 16, album: `Next Season`},
    {name: `Worry`, trackIndex: 17, album: `Next Season`},
    {name: `Listen`, trackIndex: 18, album: `Next Season`},

    {name: `Tokyo Nights`, trackIndex: 1, album: `Tokyo Nights`},

    {name: `Say My Name`, trackIndex: 1, album: `Say My Name`},

    {name: `All Falls Down`, trackIndex: 1, album: `All Falls Down`},

    {name: `Arms Around Me`, trackIndex: 1, album: `Arms Around Me`},

    {name: `Millionaire (feat. Nelly)`, trackIndex: 1, album: `Millionaire (feat. Nelly)`},

    {name: `Wanna Know`, trackIndex: 1, album: `Wanna Know`},

    {name: `True`, trackIndex: 1, album: `True`},

    {name: `Didn't Know`, trackIndex: 1, album: `Didn't Know`},

    {name: `Time Alone (feat. The Griswolds)`, trackIndex: 1, album: `Time Alone (feat. The Griswolds)`},

    {name: `Open Invite`, trackIndex: 1, album: `Open Invite`},

    {name: `Positive (feat. WRENN)`, trackIndex: 1, album: `Positive (feat. WRENN)`},

    {name: `Just Call (feat. Bella Thorne)`, trackIndex: 1, album: `Just Call (feat. Bella Thorne)`},
  ];

  constructor() {
  }

  getSongs(): Observable<Song[]> {
    return of(this.songs);
  }
}
